# docker-compose.yml
services:
  db:
    build:
      context: ./postgres-docker
    container_name: moms_hero_db
    environment:
      - POSTGRES_USER=${DB_USER}       # 從 .env 讀取 DB_USER
      - POSTGRES_PASSWORD=${DB_PASSWORD} # 從 .env 讀取 DB_PASSWORD
      - POSTGRES_DB=${DB_NAME}         # 從 .env 讀取 DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always